### ISSUE TITLE
Character Entity Use

### ISSUE THREAD

**Issue by jim-rosales** [EllenSue1667/Capstone#1]
In HTML the `&` symbol is a reserved character since it is used to add characters via an [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity).

In this case, the correct way to add a `&` symbol to your file is to do so via its entity reference. Here all you need to do is replace `&` with `&amp;`

https://github.com/EllenSue1667/Capstone/blob/fc74d81c821323acee523cba9b5a2d67a0b57de5/index.html#L64

**Comment by EllenSue1667** [comment]
I completely forgot about the symbol.  Thank you.
