### ISSUE TITLE
Alt Attribute

### ISSUE THREAD

**Issue by jim-rosales** [EllenSue1667/Capstone#2]
Excellent job making use of the alt attribute here! I did notice that some of your images did not include an alt attribute, considering it is best practice to add it in all your images next time be careful about omitting it. 

https://github.com/EllenSue1667/Capstone/blob/fc74d81c821323acee523cba9b5a2d67a0b57de5/index.html#L159

**Comment by EllenSue1667** [comment]
Thanks.  I guess I just felt like an explanation wouldn't help the user viewing the site, since the pictures didn't have any true purpose in them.  I will do better in the future.
